### PR TITLE
Patricia Manalang- css brochure form

### PR DESCRIPTION
**Pull request by patriciamanalang**
Screen Shot 2022-10-12 at 6 46 41 PM

### CODE REVIEW

**Comment by patriciamanalang** [comment]
Screen Shot 2022-10-12 at 7 07 34 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Patricia! Your border type is incorrect as compared to the example. Additionally, your SUBMIT button is misaligned, it should be placed against the right edge of the `select`. Please revise and submit a new screenshot with your revision.

**Comment by patriciamanalang** [comment]
Screen Shot 2022-10-13 at 11 05 42 PM

**Review by codingcodymiller — APPROVED** [review]
Nice work!

**Pull request merged**
